-- AlterTable
ALTER TABLE "accounts" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "customers" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "devices" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
